# Generated by Django 5.0.6 on 2024-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="default.svg", upload_to="pics"),
        ),
    ]
